package com.apiproject.diff;

public enum ChangeType {
    ENDPOINT_ADDED,
    ENDPOINT_REMOVED,
    METHOD_ADDED,
    METHOD_REMOVED,
    PATH_CHANGED,
    PARAM_ADDED,
    PARAM_REMOVED,
    PARAM_REQUIRED_CHANGED,
    PARAM_TYPE_CHANGED,
    REQUEST_BODY_CHANGED,
    RESPONSE_CHANGED,
    SCHEMA_COMPOSITION_CHANGED,
    OTHER
}
